  - name: Create EC2 Instance
    hosts: 127.0.0.1 
    connection: local
    gather_facts: False
    vars:
      keypair: myansible
    tasks:

      - name: Create a security group
        local_action: 
          module: ec2_group
          name: "{{ project_name }}_security_group"
          description: "{{ project_name }} security group"
          region: "{{ region }}"
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 443
              to_port: 443
              cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
        register: basic_firewall
    
      - name: Launch the new EC2 Instance
        ec2: 
          group: "{{ security_group }}"
          instance_type: "{{ instance_type }}" 
          image: "{{ image }}"
          wait: true 
          region: "{{ region }}"
          keypair: "{{ keypair }}"
          count: "{{ count }}"
          vpc_subnet_id: "{{ subnet }}"
          assign_public_ip: yes
        register: ec2 
    
      - name: Wait for SSH to come up
        wait_for: 
          host: "{{ item.public_ip }}"
          port: 22 
          delay: 60
          timeout: 320
          state: started
        with_items: "{{ ec2.instances }}"
    
      - name: Add tag to Instance(s)
        ec2_tag:
          resource: "{{ item.id }}"
          region: "{{ region }}"
          state: present
        with_items: "{{ ec2.instances }}"
        args:
          tags:
            Name: apache
            
      - name: Add new instance to host group
        add_host:
          hostname: "{{ item.public_ip }}"
          groupname: launched
        with_items: "{{ ec2.instances }}"

  - name: Install apache
    hosts: launched
    vars:
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ~/.ssh/myansible.pem
    become: true
    roles:
      - apache